1) В этой задаче выведите информацию о датасете, используя функцию .info()

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Leher\Downloads\disney_title.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1450 entries, 0 to 1449
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   type          1450 non-null   object
 1   title         1450 non-null   object
 2   director      977 non-null    object
 3   cast          1260 non-null   object
 4   country       1231 non-null   object
 5   release_year  1450 non-null   int64
 6   rating        1447 non-null   object
 7   duration      1450 non-null   object
 8   listed_in     1450 non-null   object
 9   description   1450 non-null   object
 10  Date          1447 non-null   object
dtypes: int64(1), object(10)
memory usage: 124.7+ KB

2) В этом задании мы поменяем тип переменной с object на datetime с помощью функции pd.to_datetime().

In [28]:
df['Date'] = pd.to_datetime(df['Date'])
df['Date'].dtype
df.info()
df

<class 'pandas.core.frame.DataFrame'>
Int64Index: 182 entries, 320 to 1449
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Type         182 non-null    object
 1   Title        182 non-null    object
 2   Director     182 non-null    object
 3   Cast         182 non-null    object
 4   Country      182 non-null    object
 5   Rating       182 non-null    object
 6   Duration     182 non-null    object
 7   Listed_In    182 non-null    string
 8   Description  182 non-null    object
 9   Date         182 non-null    datetime64[ns]
 10  Listed_In2   182 non-null    string
 11  C            182 non-null    string
dtypes: datetime64[ns](1), object(8), string(3)
memory usage: 18.5+ KB

,Type,Title,Director,Cast,Country,Rating,Duration,Listed_In,Description,Date,Listed_In2,C
320,Movie,700 Sharks,Luc Marescot,Paul Bandey,France,TV-PG,45 min,"Animals , Nature, Documentary",Follow an international team of scientists in ...,2021-01-01,"Animals , Nature, Documentary","Animals , Nature, Documentary"
322,Movie,Dr. Seuss' Horton Hears a Who!,"Jimmy Hayward, Steve Martino","Jim Carrey, Steve Carell, Will Arnett, Seth Ro...",United States,G,88 min,"Animation, Comedy, Family",Horton must save a civilization living on a sp...,2021-01-01,"Animation, Comedy, Family","Animation, Comedy, Family"
324,Movie,Mega Hammerhead,"Brandon Hill, Marc Ostrick",Neil Hammerschlag,United States,TV-PG,43 min,"Animals , Nature, Documentary",Dr. Neil Hammerschlag and his team are setting...,2021-01-01,"Animals , Nature, Documentary","Animals , Nature, Documentary"
328,Movie,Max Keeble's Big Move,Tim Hill,"Alex D. Linz, Larry Miller, Jamie Kennedy, Zen...",United States,PG,88 min,"Comedy, Family","After a week of creating mayhem, Max has to fa...",2020-12-25,"Comedy, Family","Comedy, Family"
329,Movie,Soul,Pete Docter,"Jamie Foxx, Tina Fey, Angela Bassett, Ahmir-Kh...",United States,PG,107 min,"Animation, Comedy, Family","Jamie Foxx stars in Pixar’s ""Soul,"" a comedy a...",2020-12-25,"Animation, Comedy, Family","Animation, Comedy, Family"
...,...,...,...,...,...,...,...,...,...,...,...,...
666,Movie,Marvel 75 Years: From Pulp to Pop!,Zak Knutson,"Laura Shields, Stan Lee, Alan Fine, Nicole Per...",United States,TV-PG,42 min,"Documentary, Family",See how Marvel became the top super hero story...,2020-01-01,"Documentary, Family","Documentary, Family"
670,Movie,Super Rhino,Nathan Greno,"Miley Cyrus, Mark Walton, Susie Essman, Malcol...",United States,G,4 min,"Action-Adventure, Animation, Comedy",Rhino gets an upgrade just in time to save Bol...,2020-01-01,"Action-Adventure, Animation, Comedy","Action-Adventure, Animation, Comedy"
1447,Movie,Eddie the Eagle,Dexter Fletcher,"Tom Costello, Jo Hartley, Keith Allen, Dickon ...","United Kingdom, Germany, United States",PG-13,107 min,"Biographical, Comedy, Drama","True story of Eddie Edwards, a British ski-jum...",2020-12-18,"Biographical, Comedy, Drama","Biographical, Comedy, Drama"
1448,Movie,Bend It Like Beckham,Gurinder Chadha,"Parminder Nagra, Keira Knightley, Jonathan Rhy...","United Kingdom, Germany, United States",PG-13,112 min,"Buddy, Comedy, Coming of Age",Despite the wishes of their traditional famili...,2020-09-18,"Buddy, Comedy, Coming of Age","Buddy, Comedy, Coming of Age"
1449,Movie,Captain Sparky vs. The Flying Saucers,Mark Waring,Charlie Tahan,United States,TV-G,2 min,"Action-Adventure, Animals , Nature, Animation",View one of Sparky's favorite home movies.,2020-04-01,"Action-Adventure, Animals , Nature, Animation","Action-Adventure, Animals , Nature, Animation"

3) Отфильтруйте все фильмы и сериалы, которые выходили с 1 января 2020 года по 1 января 2021 года. В результате выведите переменную с названиями десяти первых фильмов после фильтрации, с помощью функции head().

In [7]:
df = df[(df['Date'] >= '2020-01-01') & (df['Date'] <= '2021-01-01')]
df

,type,title,director,cast,country,release_year,rating,duration,listed_in,description,Date
320,Movie,700 Sharks,Luc Marescot,Paul Bandey,France,2018,TV-PG,45 min,"Animals & Nature, Documentary",Follow an international team of scientists in ...,2021-01-01
321,Movie,Big Sharks Rule,NaN,Lance Lewman,NaN,2018,TV-14,45 min,"Animals & Nature, Documentary","In the waters of South Africa, sharks reign su...",2021-01-01
322,Movie,Dr. Seuss' Horton Hears a Who!,"Jimmy Hayward, Steve Martino","Jim Carrey, Steve Carell, Will Arnett, Seth Ro...",United States,2008,G,88 min,"Animation, Comedy, Family",Horton must save a civilization living on a sp...,2021-01-01
323,Movie,Great Shark Chow Down,Mark Woodward,Dan Nachtrab,NaN,2019,TV-PG,45 min,"Animals & Nature, Documentary",Great Shark Chow Down – prepare for a feast of...,2021-01-01
324,Movie,Mega Hammerhead,"Brandon Hill, Marc Ostrick",Neil Hammerschlag,United States,2016,TV-PG,43 min,"Animals & Nature, Documentary",Dr. Neil Hammerschlag and his team are setting...,2021-01-01
...,...,...,...,...,...,...,...,...,...,...,...
672,TV Show,The Super Hero Squad,NaN,"Grey DeLisle, Steve Blum, Mikey Kelly, Charlie...",United States,2009,TV-Y7,2 Seasons,"Action-Adventure, Animation, Comedy",The greatest heroes on the planet unite to fac...,2020-01-01
673,TV Show,Year Million,NaN,Laurence Fishburne,United States,2016,TV-PG,1 Season,"Docuseries, Science Fiction","Explore what human life might be like, one mil...",2020-01-01
1447,Movie,Eddie the Eagle,Dexter Fletcher,"Tom Costello, Jo Hartley, Keith Allen, Dickon ...","United Kingdom, Germany, United States",2016,PG-13,107 min,"Biographical, Comedy, Drama","True story of Eddie Edwards, a British ski-jum...",2020-12-18
1448,Movie,Bend It Like Beckham,Gurinder Chadha,"Parminder Nagra, Keira Knightley, Jonathan Rhy...","United Kingdom, Germany, United States",2003,PG-13,112 min,"Buddy, Comedy, Coming of Age",Despite the wishes of their traditional famili...,2020-09-18
1449,Movie,Captain Sparky vs. The Flying Saucers,Mark Waring,Charlie Tahan,United States,2012,TV-G,2 min,"Action-Adventure, Animals & Nature, Animation",View one of Sparky's favorite home movies.,2020-04-01

4) Вам необходимо удалить столбец из датасета 'release_year' и вывести название оставшихся столбцов с помощью функции list().

In [8]:
columns = list(df)
columns

['type',
 'title',
 'director',
 'cast',
 'country',
 'release_year',
 'rating',
 'duration',
 'listed_in',
 'description',
 'Date']

In [9]:
df = df.drop('release_year', axis=1)
columns = list(df)
columns

['type',
 'title',
 'director',
 'cast',
 'country',
 'rating',
 'duration',
 'listed_in',
 'description',
 'Date']

5) Необходимо поменять название переменных из 'disney_title.csv' на такие же названия написанные с большой буквы

In [10]:
columns = list(df)
columns

['type',
 'title',
 'director',
 'cast',
 'country',
 'rating',
 'duration',
 'listed_in',
 'description',
 'Date']

In [13]:
newcolumns = [column.title() for column in columns]
newcolumns

['Type',
 'Title',
 'Director',
 'Cast',
 'Country',
 'Rating',
 'Duration',
 'Listed_In',
 'Description',
 'Date']

6) В этом задании вам необходимо заменить "&" на "," в столбце "listed_in", сохранить результат в новую переменную вывести последнии пять значений в новой переменной с помощью функции 'tail()'

In [19]:
df['C'] = df['Listed_In'].astype('string')
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 357 entries, 320 to 1449
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Type         357 non-null    object
 1   Title        357 non-null    object
 2   Director     209 non-null    object
 3   Cast         311 non-null    object
 4   Country      313 non-null    object
 5   Rating       357 non-null    object
 6   Duration     357 non-null    object
 7   Listed_In    357 non-null    string
 8   Description  357 non-null    object
 9   Date         357 non-null    datetime64[ns]
 10  Listed_In2   357 non-null    string
 11  C            357 non-null    string
dtypes: datetime64[ns](1), object(8), string(3)
memory usage: 36.3+ KB

,Type,Title,Director,Cast,Country,Rating,Duration,Listed_In,Description,Date,Listed_In2,C
320,Movie,700 Sharks,Luc Marescot,Paul Bandey,France,TV-PG,45 min,"Animals , Nature, Documentary",Follow an international team of scientists in ...,2021-01-01,"Animals , Nature, Documentary","Animals , Nature, Documentary"
321,Movie,Big Sharks Rule,NaN,Lance Lewman,NaN,TV-14,45 min,"Animals , Nature, Documentary","In the waters of South Africa, sharks reign su...",2021-01-01,"Animals , Nature, Documentary","Animals , Nature, Documentary"
322,Movie,Dr. Seuss' Horton Hears a Who!,"Jimmy Hayward, Steve Martino","Jim Carrey, Steve Carell, Will Arnett, Seth Ro...",United States,G,88 min,"Animation, Comedy, Family",Horton must save a civilization living on a sp...,2021-01-01,"Animation, Comedy, Family","Animation, Comedy, Family"
323,Movie,Great Shark Chow Down,Mark Woodward,Dan Nachtrab,NaN,TV-PG,45 min,"Animals , Nature, Documentary",Great Shark Chow Down – prepare for a feast of...,2021-01-01,"Animals , Nature, Documentary","Animals , Nature, Documentary"
324,Movie,Mega Hammerhead,"Brandon Hill, Marc Ostrick",Neil Hammerschlag,United States,TV-PG,43 min,"Animals , Nature, Documentary",Dr. Neil Hammerschlag and his team are setting...,2021-01-01,"Animals , Nature, Documentary","Animals , Nature, Documentary"
...,...,...,...,...,...,...,...,...,...,...,...,...
672,TV Show,The Super Hero Squad,NaN,"Grey DeLisle, Steve Blum, Mikey Kelly, Charlie...",United States,TV-Y7,2 Seasons,"Action-Adventure, Animation, Comedy",The greatest heroes on the planet unite to fac...,2020-01-01,"Action-Adventure, Animation, Comedy","Action-Adventure, Animation, Comedy"
673,TV Show,Year Million,NaN,Laurence Fishburne,United States,TV-PG,1 Season,"Docuseries, Science Fiction","Explore what human life might be like, one mil...",2020-01-01,"Docuseries, Science Fiction","Docuseries, Science Fiction"
1447,Movie,Eddie the Eagle,Dexter Fletcher,"Tom Costello, Jo Hartley, Keith Allen, Dickon ...","United Kingdom, Germany, United States",PG-13,107 min,"Biographical, Comedy, Drama","True story of Eddie Edwards, a British ski-jum...",2020-12-18,"Biographical, Comedy, Drama","Biographical, Comedy, Drama"
1448,Movie,Bend It Like Beckham,Gurinder Chadha,"Parminder Nagra, Keira Knightley, Jonathan Rhy...","United Kingdom, Germany, United States",PG-13,112 min,"Buddy, Comedy, Coming of Age",Despite the wishes of their traditional famili...,2020-09-18,"Buddy, Comedy, Coming of Age","Buddy, Comedy, Coming of Age"
1449,Movie,Captain Sparky vs. The Flying Saucers,Mark Waring,Charlie Tahan,United States,TV-G,2 min,"Action-Adventure, Animals , Nature, Animation",View one of Sparky's favorite home movies.,2020-04-01,"Action-Adventure, Animals , Nature, Animation","Action-Adventure, Animals , Nature, Animation"

In [21]:
df['Listed_In']= df['Listed_In'].str.replace('&',',')
df['Listed_In'].tail()

672               Action-Adventure, Animation, Comedy
673                       Docuseries, Science Fiction
1447                      Biographical, Comedy, Drama
1448                     Buddy, Comedy, Coming of Age
1449    Action-Adventure, Animals , Nature, Animation
Name: Listed_In, dtype: string

7) В этой задаче требуется вывести количество пропущенных значений по каждому стобцу.

In [ ]:
print(df.isnull().sum())
print(df.isnull().mean()*100)

8) В этом задании заменить пропущенные значения в стобце 'country' на 'Country not specified' с помощью функции 'fillna'.

In [30]:
df['Country'] = df['Country'].fillna('Country not specified')
print(df['Country'].head(5))

320           France
322    United States
324    United States
328    United States
329    United States
Name: Country, dtype: object

In [31]:
df

,Type,Title,Director,Cast,Country,Rating,Duration,Listed_In,Description,Date,Listed_In2,C
320,Movie,700 Sharks,Luc Marescot,Paul Bandey,France,TV-PG,45 min,"Animals , Nature, Documentary",Follow an international team of scientists in ...,2021-01-01,"Animals , Nature, Documentary","Animals , Nature, Documentary"
322,Movie,Dr. Seuss' Horton Hears a Who!,"Jimmy Hayward, Steve Martino","Jim Carrey, Steve Carell, Will Arnett, Seth Ro...",United States,G,88 min,"Animation, Comedy, Family",Horton must save a civilization living on a sp...,2021-01-01,"Animation, Comedy, Family","Animation, Comedy, Family"
324,Movie,Mega Hammerhead,"Brandon Hill, Marc Ostrick",Neil Hammerschlag,United States,TV-PG,43 min,"Animals , Nature, Documentary",Dr. Neil Hammerschlag and his team are setting...,2021-01-01,"Animals , Nature, Documentary","Animals , Nature, Documentary"
328,Movie,Max Keeble's Big Move,Tim Hill,"Alex D. Linz, Larry Miller, Jamie Kennedy, Zen...",United States,PG,88 min,"Comedy, Family","After a week of creating mayhem, Max has to fa...",2020-12-25,"Comedy, Family","Comedy, Family"
329,Movie,Soul,Pete Docter,"Jamie Foxx, Tina Fey, Angela Bassett, Ahmir-Kh...",United States,PG,107 min,"Animation, Comedy, Family","Jamie Foxx stars in Pixar’s ""Soul,"" a comedy a...",2020-12-25,"Animation, Comedy, Family","Animation, Comedy, Family"
...,...,...,...,...,...,...,...,...,...,...,...,...
666,Movie,Marvel 75 Years: From Pulp to Pop!,Zak Knutson,"Laura Shields, Stan Lee, Alan Fine, Nicole Per...",United States,TV-PG,42 min,"Documentary, Family",See how Marvel became the top super hero story...,2020-01-01,"Documentary, Family","Documentary, Family"
670,Movie,Super Rhino,Nathan Greno,"Miley Cyrus, Mark Walton, Susie Essman, Malcol...",United States,G,4 min,"Action-Adventure, Animation, Comedy",Rhino gets an upgrade just in time to save Bol...,2020-01-01,"Action-Adventure, Animation, Comedy","Action-Adventure, Animation, Comedy"
1447,Movie,Eddie the Eagle,Dexter Fletcher,"Tom Costello, Jo Hartley, Keith Allen, Dickon ...","United Kingdom, Germany, United States",PG-13,107 min,"Biographical, Comedy, Drama","True story of Eddie Edwards, a British ski-jum...",2020-12-18,"Biographical, Comedy, Drama","Biographical, Comedy, Drama"
1448,Movie,Bend It Like Beckham,Gurinder Chadha,"Parminder Nagra, Keira Knightley, Jonathan Rhy...","United Kingdom, Germany, United States",PG-13,112 min,"Buddy, Comedy, Coming of Age",Despite the wishes of their traditional famili...,2020-09-18,"Buddy, Comedy, Coming of Age","Buddy, Comedy, Coming of Age"
1449,Movie,Captain Sparky vs. The Flying Saucers,Mark Waring,Charlie Tahan,United States,TV-G,2 min,"Action-Adventure, Animals , Nature, Animation",View one of Sparky's favorite home movies.,2020-04-01,"Action-Adventure, Animals , Nature, Animation","Action-Adventure, Animals , Nature, Animation"